### ISSUE TITLE
Serialization error when adding Redshift datasource

### ISSUE THREAD

**Issue by aachenmax** [grafana/redshift-datasource#117] opened 2022-02-09 14:01 UTC
**What happened**:
I am trying to add a Redshift cluster as a datasource to my local Grafana installation. When I enter all the configuration details and click on 'Save and Test', the following error is returned:

```error executing query: SerializationError: failed decoding JSON RPC response status code: 200, request id: caused by: invalid character '<' looking for beginning of value```

I have tried it with all three available authentication options, with the same outcome.

 **What you expected to happen**:
The datasource should be added correctly if the config is correct. Otherwise, the error should be clear if it is a config issue.

**Environment**:
- Grafana version: v8.3.5
- Plugin version: v1.0.2
- OS Grafana is installed on: macOS BigSur v11.6 
- User OS & Browser: OS: macOS BigSur v11.6, Browser: Chrome Version 98.0.4758.80
- Others: aws-cli/2.4.17 Python/3.8.8 Darwin/20.6.0 exe/x86_64 prompt/off

**Comment by andresmgot** [comment] 2022-02-09 16:33
hi @aachenmax, it seems that you are getting an error but that is not properly parsed. Are you able to see any other error message either in the browser console or in the Grafana logs?

**Comment by aachenmax** [comment] 2022-02-10 13:06
Hi @andresmgot, thanks a lot for you help. The only thing i can see in the grafana.log is the following:

```
t=2022-02-10T13:58:33+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=[::1] time_ms=3 size=0 referer=
t=2022-02-10T13:58:48+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/2/health status=400 remote_addr=[::1] time_ms=2737 size=211 referer=http://localhost:3000/datasources/edit/E6wU6J-nk
```
I can also see the following in the Browser console:
<img width="870" alt="Bildschirmfoto 2022-02-10 um 14 04 58" src="https://user-images.githubusercontent.com/11407722/153414268-4f1bea62-1380-4931-9e96-777c6077c085.png">

**Comment by andresmgot** [comment] 2022-02-10 16:00
Thanks for the info @aachenmax. It seems that that does not show the root of the cause either. To try to reproduce the issue, what parameters are you using to configure Redshift? (without including sensitive information)

**Comment by iwysiu** [comment] 2022-03-14 19:04
Hi @aachenmax ! Are you still having this issue? If so, what redshift config parameters are you using (without sensitive information)?

**Comment by sunker** [comment] 2022-04-05 08:24
We've closed this issue since it needs more information and hasn't had any activity recently. We can re-open it after you you add more information. To avoid having your issue closed in the future, please read our [CONTRIBUTING](https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md) guidelines.

Happy graphing!

**Closed by sunker** 2022-04-05 08:24 UTC
Labels: type/bug, datasource/Redshift, needs more info
